query getPayments($data: PaymentsListInput!) {
  payments(data: $data) {
    id
    userEmail
    userLastName
    userFirstName
    typeName
    typeTranslationKey
    frequency
    paymentType {
      compensationBaseTypeId
      name
      translationKey
    }
    contractId
    properties {
      amount
      title
      monthlyHours
    }
  }
}

query getPaymentsByContractId($data: PaymentsListInput!) {
  payments(data: $data) {
    id
    contractId
    userEmail
    userFirstName
    userLastName
    typeName
    typeTranslationKey
    frequency
    paymentType {
      compensationBaseTypeId
      name
      translationKey
    }
    properties {
      amount
      title
      monthlyHours
    }
  }
}

query getEmployeeById($data: GetEmployeeInput!) {
  employee(data: $data) {
    id
    firstName
    lastName
    employeeContract {
      id
      contractStart
      contractEnd
    }
  }
}
